sudo: false
dist: trusty
language: node_js

branches:
  only:
    - master
    - dev

cache:
  yarn: true

matrix:
  include:
    - os: linux
      node_js: "8"
      env: NO_WATCH_TESTS=1 JOB_PART=lint
    - os: linux
      node_js: "8"
      env: NO_WATCH_TESTS=1 JOB_PART=integration
    - os: linux
      node_js: "8"
      env: NO_WATCH_TESTS=1 JOB_PART=unit
    - os: linux
      node_js: "6"
      env: NO_WATCH_TESTS=1 JOB_PART=integration
    - os: osx
      node_js: "8"
      env: NO_WATCH_TESTS=1 JOB_PART=integration
  allow_failures:
    - os: osx

fast_finish: true
