sudo: false
dist: trusty
language: node_js

branches:
  only:
    - master
    - dev

cache:
  yarn: true

matrix:
  include:
    - os: linux
      node_js: "8"
      env: NO_WATCH_TESTS=1 JOB_PART=build

fast_finish: true
