/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LiftoffRouteImport } from './routes/liftoff'
import { Route as IndexRouteImport } from './routes/index'

const LiftoffRoute = LiftoffRouteImport.update({
  id: '/liftoff',
  path: '/liftoff',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/liftoff': typeof LiftoffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/liftoff': typeof LiftoffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/liftoff': typeof LiftoffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/liftoff'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/liftoff'
  id: '__root__' | '/' | '/liftoff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiftoffRoute: typeof LiftoffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/liftoff': {
      id: '/liftoff'
      path: '/liftoff'
      fullPath: '/liftoff'
      preLoaderRoute: typeof LiftoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiftoffRoute: LiftoffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
