/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BlastoffRouteImport } from './routes/blastoff'
import { Route as IndexRouteImport } from './routes/index'

const BlastoffRoute = BlastoffRouteImport.update({
  id: '/blastoff',
  path: '/blastoff',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blastoff': typeof BlastoffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blastoff': typeof BlastoffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blastoff': typeof BlastoffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blastoff'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blastoff'
  id: '__root__' | '/' | '/blastoff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlastoffRoute: typeof BlastoffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/blastoff': {
      id: '/blastoff'
      path: '/blastoff'
      fullPath: '/blastoff'
      preLoaderRoute: typeof BlastoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlastoffRoute: BlastoffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
